#!/bin/bash

export KERNELNAME=Deagle

export LOCALVERSION=V2

export KBUILD_BUILD_USER=builder

export KBUILD_BUILD_HOST=deagle

export TOOLCHAIN=clang

export DEVICES=whyred,tulip,wayne

source helper

gen_toolchain

send_msg "Start building..."

START=$(date +"%s")

for i in ${DEVICES//,/ }
do
	build_nonoc ${i} "oldcam"

	build_nonoc ${i} "newcam"
done

for i in ${DEVICES//,/ }
do
        build_oc ${i} "oldcam"

        build_oc ${i} "newcam"
done

END=$(date +"%s")

DIFF=$(( END - START ))

send_msg "Build complete in $((DIFF / 60))m $((DIFF % 60))s"

