#!/bin/bash

export KERNELNAME=Deagle

export LOCALVERSION=V14

export KBUILD_BUILD_USER=builder

export KBUILD_BUILD_HOST=deagle

export TOOLCHAIN=clang

export DEVICES=whyred,tulip,wayne

export TOKEN=1589576060:AAHy12j9US6KcNUgUaInYTC_aP2XJI-vZps

export GRUP=-1001362420513

source helper

gen_toolchain

send_msg "Start building..."

send_pesan "Start building..."

START=$(date +"%s")

for i in ${DEVICES//,/ }
do
	build ${i} -oldcam

	build ${i} -newcam
done

send_msg "Build OC..."

send_pesan "Build OC..."

git apply oc.patch

for i in ${DEVICES//,/ }
do
	if [ $i == "whyred" ] || [ $i == "tulip" ]
	then
		build ${i} -oldcam -overclock

		build ${i} -newcam -overclock
	fi
done

END=$(date +"%s")

DIFF=$(( END - START ))

send_msg "Build complete in $((DIFF / 60))m $((DIFF % 60))s"

send_pesan "Build complete in $((DIFF / 60))m $((DIFF % 60))s"
